# This is a basic workflow to help you get started with Actions
name: Publish to Powershell Gallery

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'staging'
  release:
    types: [published]
    
jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get-name
        run: |
            echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Publish-Module -Path "$($env:GITHUB_WORKSPACE)/$($env:REPO_NAME)" -NuGetApiKey $env:NUGET_KEY -Verbose
